# settings-dev.yaml
name: "go-gin"
port: 8022
logsAddress: "./logs/"

mysql:
  name: "guestuser"
  host: "web-mysql"
  port: 3306
  dbName: "go-gin"
  password: "secret123"


redis:
  host: "web-redis"
  port: 6379

jwt:
  key: "EYsnfKMf5XWk87LASEs28Dj5ZqGkSerH"

minio:
  endpoint: "127.0.0.1:9000"
  accessKeyID: "minioadmin"
  secretAccessKey: "minioadmin"

